#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    sum=0
    for m in range(len(arr)):
        for n in range((len(arr)-1)-m):
            if arr[n+1]<arr[n]:
                temp=arr[n]
                arr[n]=arr[n+1]
                arr[n+1]=temp    
    for i in range(len(arr)-1):
        sum+=arr[i]
    print(sum,end=" ")
    sum=0
    for j in range(1,len(arr)):   
        sum+=arr[j]
    print(sum)

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
