#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the staircase function below.
def staircase(n):
    temp=n
    for i in range(n):  
            for j in range(temp-1):
                print("",end=" ")
            for k in range(i+1):
                print("#",end="")
            temp-=1 
            print("")  
            
                 
                

if __name__ == '__main__':
    n = int(input())

    staircase(n)
